### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by frapac** [exanauts/ExaPF.jl#143]
This issue is opened to track the remaining points to address before the release 0.5.0

- [x] Discuss together the naming of the functions exposed in the API, and check the consistency of the signatures (#146)
- [x] Change signature of `DirectSolver` to allow storing the `Factorization` (breaking change) (#144)
- [x] Fix warning issued when loading ExaPF: ` Warning: Replacing docs for ExaPF.bounds :: Union{} in module ExaPF` (#146)
- [x] Check that all Julia scripts in `scripts/` are working (#146)
- [ ] Add in `benchmarks` the script to reproduce the results presented at JuliaCon 
- [x] Check that ProxAL is working on ExaPF#develop (https://github.com/exanauts/ProxAL.jl/runs/2331420226)
- [x] Finish updating the documentation (#148) 
- [x] Update README (#148)
