### ISSUE TITLE
ExaPF 0.6

### ISSUE THREAD

**Issue by frapac** [exanauts/ExaPF.jl#180]
This issue lists the remaining TODOs required before releasing ExaPF 0.6

#### New features 
- [x] Multiple generators per buses (#168 )
- [ ] Merge new overlapping Schwarz preconditioner (#86 )
- [x] Integration of batch Hessian (PR #179 #185)
- [x] Figure out new interface for `LinearSolvers` (PR #176 )

#### Refactoring 
- [x] Move all `Evaluators` in a separate package (#191 )
- [ ] Move all CUDA related code in a subpackage in ExaPF (#175 )
- [ ] Clean API of ExaPF (operational constraints in Polar)

#### Fixes
- [x] Fix invalidations (PR #182 )
- [x] Solve issue with `allowscalar` on `CUDA.jl v3.3` (#80 )

**Comment by frapac** [comment]
Closed by #208
